steps:
  submodules:
    image: alpine/git
    commands:
      - git submodule update --init --recursive
  build:
    image: plugins/hugo
    settings:
      hugo_version: 0.109.0
      extended: true
      validate: false
  deploy:
    image: appleboy/drone-scp:linux-arm64
    settings:
      host: openssh-server.files
      username: jcm
      password:
        from_secret: ssh_password
      port: 2222
      target: /config/data/blog/
      source: public/
      strip_components: 1
