baseURL = 'https://blog.jcm.re/'
languageCode = 'en-us'
title = "JCM's Blog"
theme = "hello-friend-ng"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

enableRobotsTXT = true
enableEmoji     = true
enableGitInfo   = true
disableRSS     = false
disableSitemap = false
disable404     = false

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

[services]
  [services.rss]
    limit = 100

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "My simple personal blog"
  gitUrl = "https://git.jcm.re/jcm/blog/commit/"

  disableReadOtherPosts = false
  enableSharingButtons = true
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "My simple personal blog"
  keywords = "homepage, blog"
  images = [""]

  [params.author]
    name = "JCM"

  [params.footer]
    rss = true
    copyright = true
    author = true
    bottomText = [
      "Powered by <a href=\"https://gohugo.io\">Hugo</a>",
      "Using a <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">cool theme</a> by <a href=\"https://github.com/rhazdon\">rhazdon</a>",
      "Check out the <a href=\"https://git.jcm.re/jcm/blog\">source</a>!"
    ]

  [params.logo]
    logoMark     = "$"
    logoText     = "./blog"
    logoHomeLink = "/"

  [[params.social]]
    name = "web"
    url = "https://jcm.re"

  [[params.social]]
    name = "github"
    url = "https://github.com/JnCrMx"

  [[params.social]]
    name = "gitea"
    url = "https://git.jcm.re/jcm"

  [[params.social]]
    name = "bluesky"
    url = "https://bsky.app/profile/jcm.re"

  [[params.social]]
    name = "mastodon"
    url = "https://social.jcm.re/@jcm"

  [[params.social]]
    name = "email"
    url = "mailto:jcm@jcm.re"

  [[params.social]]
    name = "gpg"
    url = "https://keys.openpgp.org/vks/v1/by-fingerprint/7B839F0DA64069DD7832BB802F536DE3E9EC3AD8"

[languages]
  [languages.en]
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>'
